name: Update Timestamp

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
    inputs:
      custom_message:
        description: ''
        required: false
        default: 'Manual update'

permissions:
  contents: write

jobs:
  update-timestamp:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master

      - name: Update Timestamp File
        run: |
          current_time=$(date '+%Y-%m-%d %H:%M:%S')
          echo "Last updated: $current_time" > timestamp.txt

      - name: Configure Git
        run: |
          git config user.name "recitativonika"
          git config user.email "fool-body-cheddar@duck.com"

      - name: Commit and Push Changes
        env:
          CUSTOM_MSG: ${{ inputs.custom_message }}
        run: |
          if [[ $(git status --porcelain timestamp.txt) ]]; then
            if [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "$CUSTOM_MSG" ]]; then
              commit_message="$CUSTOM_MSG - $(date '+%Y-%m-%d %H:%M:%S')"
            else
              commit_messages=(
                "Auto update timestamp"
                "Scheduled timestamp refresh"
                "Regular activity log update"
                "30-minute status sync"
                "Timestamp maintenance"
              )
              random_msg=${commit_messages[$RANDOM % ${#commit_messages[@]}]}
              commit_message="$random_msg - $(date '+%Y-%m-%d %H:%M:%S')"
            fi
            
            git add timestamp.txt
            git commit -m "$commit_message"
            git push origin master  # Push ke branch master
          fi
